BEGIN;

-- Especialidades JA: Estudio de la naturaleza (157 honors)
-- Prerequisite: ESPECIALIDADES_SECCIONES_SCHEMA.sql
-- Idempotent: upserts section, inserts missing honors, updates seccion_id on matches

INSERT INTO public.especialidad_secciones (slug, nombre, orden, estado, fuente_url)
VALUES ('estudio-de-la-naturaleza', 'Estudio de la naturaleza', 7, 'activo', 'https://www.guiasmayores.com/especialidades-ja---estudio-de-la-naturaleza.html')
ON CONFLICT (slug) DO UPDATE SET
  nombre = EXCLUDED.nombre,
  orden = EXCLUDED.orden,
  fuente_url = EXCLUDED.fuente_url,
  updated_at = now();

WITH src(nombre) AS (
  VALUES
    ('Abejas y avispas'),
    ('Acacias'),
    ('Acuarios'),
    ('Agricultura ecológica'),
    ('Algas marinas'),
    ('Anfibios'),
    ('Anfibios - Avanzado'),
    ('Animales domésticos'),
    ('Animales migratorios'),
    ('Animales nocivos'),
    ('Animales nocturnos'),
    ('Animales venenosos'),
    ('Antílopes'),
    ('Antílopes - Avanzado'),
    ('Arácnidos'),
    ('Árboles'),
    ('Árboles - Avanzado'),
    ('Arbustos'),
    ('Arbustos - Avanzado'),
    ('Arena'),
    ('Arrecifes de Coral'),
    ('Arrecifes de coral - Avanzado'),
    ('Aves'),
    ('Aves - Avanzado'),
    ('Aves australianas'),
    ('Aves de jaula'),
    ('Aves de rapiña'),
    ('Aves de rapiña - Avanzado'),
    ('Aves de rapiña (División Sudamericana)'),
    ('Aves domésticas'),
    ('Azúcar de Arce'),
    ('Azúcar de Arce - Avanzado'),
    ('Bacterias'),
    ('Bioconstrucción'),
    ('Bosques templados caducifolios'),
    ('Briófitas'),
    ('Bromelias'),
    ('Burbujas'),
    ('Cactus'),
    ('Cactus - Avanzado'),
    ('Camellos'),
    ('Camuflaje animal'),
    ('Camuflaje animal - Avanzado'),
    ('Carbón'),
    ('Cataratas'),
    ('Cetáceos'),
    ('Ciencia de agua'),
    ('Ciencia de agua - Avanzado'),
    ('Ciencia del clima'),
    ('Ciencia del clima - Avanzado'),
    ('Ciencia planetaria'),
    ('Cigarras'),
    ('Citología'),
    ('Climatología'),
    ('Combustibles alternativos'),
    ('Combustibles alternativos - Avanzado'),
    ('Compostaje casero'),
    ('Conservación ambiental'),
    ('Coquí'),
    ('Coquí - Avanzado'),
    ('Cosmografía'),
    ('Cosmografía - Avanzado'),
    ('Crustáceos'),
    ('Cuidado y entrenamiento de perros'),
    ('Dinosaurios'),
    ('Dunas'),
    ('Dunas - Avanzado'),
    ('Ecología'),
    ('Ecología - Avanzado'),
    ('Energía renovable'),
    ('Energías renovables'),
    ('Especies en peligro de extinción'),
    ('Estuarios'),
    ('Eucaliptos'),
    ('Fauna marina'),
    ('Fisiología vegetal'),
    ('Flores'),
    ('Flores - Avanzado'),
    ('Fósiles'),
    ('Gatos'),
    ('Gatos - Avanzado'),
    ('Geología'),
    ('Geología - Avanzado'),
    ('Glaciares'),
    ('Gramíneas'),
    ('Helechos'),
    ('Hierbas'),
    ('Hongos'),
    ('Hormigas'),
    ('Huellas de animales'),
    ('Huellas de animales - Avanzado'),
    ('Insectos'),
    ('Insectos - Avanzado'),
    ('Invertebrados marinos'),
    ('Líquenes'),
    ('Líquenes, hepáticas y musgos'),
    ('Lombrices'),
    ('Lombrices - Avanzado'),
    ('Loros y cacatúas'),
    ('Mamíferos'),
    ('Mamíferos - Avanzado'),
    ('Mamíferos marinos'),
    ('Mamíferos pequeños como mascotas'),
    ('Mariposas'),
    ('Marsupiales'),
    ('Medio ambiente acuático'),
    ('Medio ambiente terrestre'),
    ('Meteoritos'),
    ('Migración'),
    ('Mineralogía'),
    ('Mineralogía - Avanzado'),
    ('Moluscos'),
    ('Moluscos - Avanzado'),
    ('Moluscos terrestres y de agua dulce'),
    ('Montañas'),
    ('Murciélagos'),
    ('Murciélagos - Avanzado'),
    ('Océanos'),
    ('Odonatos'),
    ('Odonatos - Avanzado'),
    ('Orquídeas'),
    ('Orquídeas - Avanzado'),
    ('Palmeras'),
    ('Pantanos y ciénagas'),
    ('Pantanos y ciénagas - Avanzado'),
    ('Papagayos, loros y pericos'),
    ('Pastizales templados'),
    ('Pastizales templados - Avanzado'),
    ('Peces'),
    ('Peces ornamentales'),
    ('Perros'),
    ('Plantas carnívoras'),
    ('Plantas de interior'),
    ('Plantas depredadoras'),
    ('Plantas silvestres comestibles'),
    ('Poríferos y cnidarios'),
    ('Preservación de recursos hídricos'),
    ('Primates'),
    ('Protozoarios'),
    ('Reciclaje'),
    ('Reciclaje - Avanzado'),
    ('Recogida selectiva'),
    ('Reptiles'),
    ('Reptiles - Avanzado'),
    ('Ríos y arroyos'),
    ('Ríos y arroyos - Avanzado'),
    ('Selvas pluviales'),
    ('Semillas'),
    ('Semillas - Avanzado'),
    ('Sol de medianoche'),
    ('Suelos y terrenos'),
    ('Taiga'),
    ('Taiga - Avanzado'),
    ('Tiburones'),
    ('Tortugas'),
    ('Vida microscópica'),
    ('Volcanes')
),
club_tipos AS (
  SELECT nombre FROM public.tipos_club
  WHERE nombre ILIKE 'Conquistador%'
     OR nombre ILIKE 'Gu%Mayor%'
     OR nombre ILIKE 'Master Guide%'
),
resolved AS (
  SELECT src.nombre, s.id AS seccion_id, ct.nombre AS club_tipo
  FROM src
  JOIN public.especialidad_secciones s ON s.slug = 'estudio-de-la-naturaleza'
  CROSS JOIN club_tipos ct
)
INSERT INTO public.especialidades (nombre, club_tipo, seccion_id)
SELECT r.nombre, r.club_tipo, r.seccion_id
FROM resolved r
WHERE NOT EXISTS (
  SELECT 1 FROM public.especialidades e
  WHERE lower(trim(e.nombre)) = lower(trim(r.nombre))
    AND e.club_tipo = r.club_tipo
);

-- Link existing honors (same name) to this section if seccion_id is missing or wrong
UPDATE public.especialidades e
SET seccion_id = s.id
FROM public.especialidad_secciones s,
     (VALUES
       ('Abejas y avispas'),
       ('Acacias'),
       ('Acuarios'),
       ('Agricultura ecológica'),
       ('Algas marinas'),
       ('Anfibios'),
       ('Anfibios - Avanzado'),
       ('Animales domésticos'),
       ('Animales migratorios'),
       ('Animales nocivos'),
       ('Animales nocturnos'),
       ('Animales venenosos'),
       ('Antílopes'),
       ('Antílopes - Avanzado'),
       ('Arácnidos'),
       ('Árboles'),
       ('Árboles - Avanzado'),
       ('Arbustos'),
       ('Arbustos - Avanzado'),
       ('Arena'),
       ('Arrecifes de Coral'),
       ('Arrecifes de coral - Avanzado'),
       ('Aves'),
       ('Aves - Avanzado'),
       ('Aves australianas'),
       ('Aves de jaula'),
       ('Aves de rapiña'),
       ('Aves de rapiña - Avanzado'),
       ('Aves de rapiña (División Sudamericana)'),
       ('Aves domésticas'),
       ('Azúcar de Arce'),
       ('Azúcar de Arce - Avanzado'),
       ('Bacterias'),
       ('Bioconstrucción'),
       ('Bosques templados caducifolios'),
       ('Briófitas'),
       ('Bromelias'),
       ('Burbujas'),
       ('Cactus'),
       ('Cactus - Avanzado'),
       ('Camellos'),
       ('Camuflaje animal'),
       ('Camuflaje animal - Avanzado'),
       ('Carbón'),
       ('Cataratas'),
       ('Cetáceos'),
       ('Ciencia de agua'),
       ('Ciencia de agua - Avanzado'),
       ('Ciencia del clima'),
       ('Ciencia del clima - Avanzado'),
       ('Ciencia planetaria'),
       ('Cigarras'),
       ('Citología'),
       ('Climatología'),
       ('Combustibles alternativos'),
       ('Combustibles alternativos - Avanzado'),
       ('Compostaje casero'),
       ('Conservación ambiental'),
       ('Coquí'),
       ('Coquí - Avanzado'),
       ('Cosmografía'),
       ('Cosmografía - Avanzado'),
       ('Crustáceos'),
       ('Cuidado y entrenamiento de perros'),
       ('Dinosaurios'),
       ('Dunas'),
       ('Dunas - Avanzado'),
       ('Ecología'),
       ('Ecología - Avanzado'),
       ('Energía renovable'),
       ('Energías renovables'),
       ('Especies en peligro de extinción'),
       ('Estuarios'),
       ('Eucaliptos'),
       ('Fauna marina'),
       ('Fisiología vegetal'),
       ('Flores'),
       ('Flores - Avanzado'),
       ('Fósiles'),
       ('Gatos'),
       ('Gatos - Avanzado'),
       ('Geología'),
       ('Geología - Avanzado'),
       ('Glaciares'),
       ('Gramíneas'),
       ('Helechos'),
       ('Hierbas'),
       ('Hongos'),
       ('Hormigas'),
       ('Huellas de animales'),
       ('Huellas de animales - Avanzado'),
       ('Insectos'),
       ('Insectos - Avanzado'),
       ('Invertebrados marinos'),
       ('Líquenes'),
       ('Líquenes, hepáticas y musgos'),
       ('Lombrices'),
       ('Lombrices - Avanzado'),
       ('Loros y cacatúas'),
       ('Mamíferos'),
       ('Mamíferos - Avanzado'),
       ('Mamíferos marinos'),
       ('Mamíferos pequeños como mascotas'),
       ('Mariposas'),
       ('Marsupiales'),
       ('Medio ambiente acuático'),
       ('Medio ambiente terrestre'),
       ('Meteoritos'),
       ('Migración'),
       ('Mineralogía'),
       ('Mineralogía - Avanzado'),
       ('Moluscos'),
       ('Moluscos - Avanzado'),
       ('Moluscos terrestres y de agua dulce'),
       ('Montañas'),
       ('Murciélagos'),
       ('Murciélagos - Avanzado'),
       ('Océanos'),
       ('Odonatos'),
       ('Odonatos - Avanzado'),
       ('Orquídeas'),
       ('Orquídeas - Avanzado'),
       ('Palmeras'),
       ('Pantanos y ciénagas'),
       ('Pantanos y ciénagas - Avanzado'),
       ('Papagayos, loros y pericos'),
       ('Pastizales templados'),
       ('Pastizales templados - Avanzado'),
       ('Peces'),
       ('Peces ornamentales'),
       ('Perros'),
       ('Plantas carnívoras'),
       ('Plantas de interior'),
       ('Plantas depredadoras'),
       ('Plantas silvestres comestibles'),
       ('Poríferos y cnidarios'),
       ('Preservación de recursos hídricos'),
       ('Primates'),
       ('Protozoarios'),
       ('Reciclaje'),
       ('Reciclaje - Avanzado'),
       ('Recogida selectiva'),
       ('Reptiles'),
       ('Reptiles - Avanzado'),
       ('Ríos y arroyos'),
       ('Ríos y arroyos - Avanzado'),
       ('Selvas pluviales'),
       ('Semillas'),
       ('Semillas - Avanzado'),
       ('Sol de medianoche'),
       ('Suelos y terrenos'),
       ('Taiga'),
       ('Taiga - Avanzado'),
       ('Tiburones'),
       ('Tortugas'),
       ('Vida microscópica'),
       ('Volcanes')
     ) AS src(nombre)
WHERE s.slug = 'estudio-de-la-naturaleza'
  AND lower(trim(e.nombre)) = lower(trim(src.nombre))
  AND e.seccion_id IS DISTINCT FROM s.id;

COMMIT;
