-- =============================================================================
-- Especialidades JA import from guiasmayores.com (scraped section index pages)
-- Generated: 2026-06-14
-- Total sections: 8, total honors: 753
-- Run ESPECIALIDADES_SECCIONES_SCHEMA.sql first
-- =============================================================================

BEGIN;

-- Sections (upsert by slug)
INSERT INTO public.especialidad_secciones (slug, nombre, orden, estado, fuente_url)
VALUES ('actividades-agropecuarias', 'Actividades agropecuarias', 1, 'activo', 'https://www.guiasmayores.com/especialidades-ja---actividades-agropecuarias.html')
ON CONFLICT (slug) DO UPDATE SET
  nombre = EXCLUDED.nombre,
  orden = EXCLUDED.orden,
  fuente_url = EXCLUDED.fuente_url,
  updated_at = now();

INSERT INTO public.especialidad_secciones (slug, nombre, orden, estado, fuente_url)
VALUES ('artes-y-actividades-manuales', 'Artes y actividades manuales', 2, 'activo', 'https://www.guiasmayores.com/especialidades-ja---artes-y-actividades-manuales.html')
ON CONFLICT (slug) DO UPDATE SET
  nombre = EXCLUDED.nombre,
  orden = EXCLUDED.orden,
  fuente_url = EXCLUDED.fuente_url,
  updated_at = now();

INSERT INTO public.especialidad_secciones (slug, nombre, orden, estado, fuente_url)
VALUES ('actividades-recreacionales', 'Actividades recreacionales', 3, 'activo', 'https://www.guiasmayores.com/especialidades-ja---actividades-recreacionales.html')
ON CONFLICT (slug) DO UPDATE SET
  nombre = EXCLUDED.nombre,
  orden = EXCLUDED.orden,
  fuente_url = EXCLUDED.fuente_url,
  updated_at = now();

INSERT INTO public.especialidad_secciones (slug, nombre, orden, estado, fuente_url)
VALUES ('actividades-vocacionales', 'Artes vocacionales', 4, 'activo', 'https://www.guiasmayores.com/especialidades-ja---actividades-vocacionales.html')
ON CONFLICT (slug) DO UPDATE SET
  nombre = EXCLUDED.nombre,
  orden = EXCLUDED.orden,
  fuente_url = EXCLUDED.fuente_url,
  updated_at = now();

INSERT INTO public.especialidad_secciones (slug, nombre, orden, estado, fuente_url)
VALUES ('artes-domesticas', 'Artes domésticas', 5, 'activo', 'https://www.guiasmayores.com/especialidades-ja---artes-domeacutesticas.html')
ON CONFLICT (slug) DO UPDATE SET
  nombre = EXCLUDED.nombre,
  orden = EXCLUDED.orden,
  fuente_url = EXCLUDED.fuente_url,
  updated_at = now();

INSERT INTO public.especialidad_secciones (slug, nombre, orden, estado, fuente_url)
VALUES ('crecimiento-espiritual', 'Crecimiento espiritual, actividades misioneras y herencia', 6, 'activo', 'https://www.guiasmayores.com/especialidades-ja---crecimiento-espiritual-actividades-misioneras-y-herencia.html')
ON CONFLICT (slug) DO UPDATE SET
  nombre = EXCLUDED.nombre,
  orden = EXCLUDED.orden,
  fuente_url = EXCLUDED.fuente_url,
  updated_at = now();

INSERT INTO public.especialidad_secciones (slug, nombre, orden, estado, fuente_url)
VALUES ('estudio-de-la-naturaleza', 'Estudio de la naturaleza', 7, 'activo', 'https://www.guiasmayores.com/especialidades-ja---estudio-de-la-naturaleza.html')
ON CONFLICT (slug) DO UPDATE SET
  nombre = EXCLUDED.nombre,
  orden = EXCLUDED.orden,
  fuente_url = EXCLUDED.fuente_url,
  updated_at = now();

INSERT INTO public.especialidad_secciones (slug, nombre, orden, estado, fuente_url)
VALUES ('salud-y-ciencia', 'Salud y ciencia', 8, 'activo', 'https://www.guiasmayores.com/especialidades-ja---salud-y-ciencia.html')
ON CONFLICT (slug) DO UPDATE SET
  nombre = EXCLUDED.nombre,
  orden = EXCLUDED.orden,
  fuente_url = EXCLUDED.fuente_url,
  updated_at = now();

-- Honors (upsert by section + normalized name)
-- Applies to Conquistadores and Guías Mayores / Master Guide club types when present
WITH src(nombre, seccion_slug) AS (
  VALUES
    ('Agricultura', 'actividades-agropecuarias'),
    ('Agricultura de subsistencia', 'actividades-agropecuarias'),
    ('Apicultura', 'actividades-agropecuarias'),
    ('Avicultura', 'actividades-agropecuarias'),
    ('Colombofilia', 'actividades-agropecuarias'),
    ('Cría de caballos', 'actividades-agropecuarias'),
    ('Cría de cabras', 'actividades-agropecuarias'),
    ('Cría de ovejas', 'actividades-agropecuarias'),
    ('Floricultura', 'actividades-agropecuarias'),
    ('Frutas pequeñas', 'actividades-agropecuarias'),
    ('Fruticultura', 'actividades-agropecuarias'),
    ('Ganadería', 'actividades-agropecuarias'),
    ('Hidroponía y acuaponía', 'actividades-agropecuarias'),
    ('Hidroponía y acuaponía - Avanzado', 'actividades-agropecuarias'),
    ('Jardinería', 'actividades-agropecuarias'),
    ('Lechería', 'actividades-agropecuarias'),
    ('Especialidad JA Paisajismo', 'actividades-agropecuarias'),
    ('Pesca isleña', 'actividades-agropecuarias'),
    ('Adinkra', 'artes-y-actividades-manuales'),
    ('Aeromodelismo', 'artes-y-actividades-manuales'),
    ('Álbum de recortes', 'artes-y-actividades-manuales'),
    ('Álbum de recortes - Avanzado', 'artes-y-actividades-manuales'),
    ('Alfarería', 'artes-y-actividades-manuales'),
    ('Amigurumi', 'artes-y-actividades-manuales'),
    ('Arte callejero', 'artes-y-actividades-manuales'),
    ('Arte de envolver regalos', 'artes-y-actividades-manuales'),
    ('Arte de hacer tarjetas', 'artes-y-actividades-manuales'),
    ('Arte de hacer velas', 'artes-y-actividades-manuales'),
    ('Arte digital', 'artes-y-actividades-manuales'),
    ('Arte en bambú', 'artes-y-actividades-manuales'),
    ('Arte en hilo', 'artes-y-actividades-manuales'),
    ('Arte en masa de pan', 'artes-y-actividades-manuales'),
    ('Arte en plástico', 'artes-y-actividades-manuales'),
    ('Artesanía', 'artes-y-actividades-manuales'),
    ('Artes y trabajos indígenas', 'artes-y-actividades-manuales'),
    ('Artes y trabajos indígenas - Avanzado', 'artes-y-actividades-manuales'),
    ('Automodelismo', 'artes-y-actividades-manuales'),
    ('Azulejos de mosaico', 'artes-y-actividades-manuales'),
    ('Bordado en punto cruz', 'artes-y-actividades-manuales'),
    ('Botemodelismo', 'artes-y-actividades-manuales'),
    ('Cantar', 'artes-y-actividades-manuales'),
    ('Cerámica', 'artes-y-actividades-manuales'),
    ('Cestería', 'artes-y-actividades-manuales'),
    ('Cinta americana', 'artes-y-actividades-manuales'),
    ('Cohetemodelismo', 'artes-y-actividades-manuales'),
    ('Cohetemodelismo - Avanzado', 'artes-y-actividades-manuales'),
    ('Construcción con LEGO®', 'artes-y-actividades-manuales'),
    ('Construcción nativa', 'artes-y-actividades-manuales'),
    ('Crochet', 'artes-y-actividades-manuales'),
    ('Crochet - Avanzado', 'artes-y-actividades-manuales'),
    ('Cultura taína', 'artes-y-actividades-manuales'),
    ('Decoración', 'artes-y-actividades-manuales'),
    ('Decoración de pasteles', 'artes-y-actividades-manuales'),
    ('Découpage', 'artes-y-actividades-manuales'),
    ('Derbi de automodelos de pino', 'artes-y-actividades-manuales'),
    ('Derbi de automodelos de pino - Avanzado', 'artes-y-actividades-manuales'),
    ('Dibujo', 'artes-y-actividades-manuales'),
    ('Dibujo - Avanzado', 'artes-y-actividades-manuales'),
    ('Dibujo vectorial', 'artes-y-actividades-manuales'),
    ('Escultura', 'artes-y-actividades-manuales'),
    ('Esmaltado en cobre', 'artes-y-actividades-manuales'),
    ('Esmaltado en cobre - Avanzado', 'artes-y-actividades-manuales'),
    ('E.V.A. (Etilvinilacetato)', 'artes-y-actividades-manuales'),
    ('Falda escocesa', 'artes-y-actividades-manuales'),
    ('Falda escocesa - Avanzado', 'artes-y-actividades-manuales'),
    ('Faros', 'artes-y-actividades-manuales'),
    ('Faros - Avanzado', 'artes-y-actividades-manuales'),
    ('Filatelia', 'artes-y-actividades-manuales'),
    ('Filatelia - Avanzado', 'artes-y-actividades-manuales'),
    ('Filigrana en papel', 'artes-y-actividades-manuales'),
    ('Filigrana en papel - Avanzado', 'artes-y-actividades-manuales'),
    ('Flores fuxico', 'artes-y-actividades-manuales'),
    ('Fotografía', 'artes-y-actividades-manuales'),
    ('Fotografía digital', 'artes-y-actividades-manuales'),
    ('Gaita', 'artes-y-actividades-manuales'),
    ('Gaita - Avanzado', 'artes-y-actividades-manuales'),
    ('Genealogía', 'artes-y-actividades-manuales'),
    ('Genealogía - Avanzado', 'artes-y-actividades-manuales'),
    ('Globo aerostático', 'artes-y-actividades-manuales'),
    ('Globoflexia', 'artes-y-actividades-manuales'),
    ('Globoflexia - Avanzado', 'artes-y-actividades-manuales'),
    ('Grabado en vidrio', 'artes-y-actividades-manuales'),
    ('Guitarra', 'artes-y-actividades-manuales'),
    ('Guitarra - Avanzado', 'artes-y-actividades-manuales'),
    ('Herencia cultural', 'artes-y-actividades-manuales'),
    ('Hilado', 'artes-y-actividades-manuales'),
    ('Historietas animadas', 'artes-y-actividades-manuales'),
    ('Indumentaria de cuello', 'artes-y-actividades-manuales'),
    ('Intercambio de pins', 'artes-y-actividades-manuales'),
    ('Intercambio de pins - Avanzado', 'artes-y-actividades-manuales'),
    ('Lapidación', 'artes-y-actividades-manuales'),
    ('Lettering', 'artes-y-actividades-manuales'),
    ('Letreros y carteles', 'artes-y-actividades-manuales'),
    ('Kanzashi', 'artes-y-actividades-manuales'),
    ('Macramé', 'artes-y-actividades-manuales'),
    ('Modelo de papel', 'artes-y-actividades-manuales'),
    ('Modelado en yeso', 'artes-y-actividades-manuales'),
    ('Música', 'artes-y-actividades-manuales'),
    ('Música - Avanzado', 'artes-y-actividades-manuales'),
    ('Noken', 'artes-y-actividades-manuales'),
    ('Numismática', 'artes-y-actividades-manuales'),
    ('Numismática - Avanzado', 'artes-y-actividades-manuales'),
    ('Origami', 'artes-y-actividades-manuales'),
    ('Origami - Avanzado', 'artes-y-actividades-manuales'),
    ('Ornamentación floral', 'artes-y-actividades-manuales'),
    ('Papel maché', 'artes-y-actividades-manuales'),
    ('Pintura', 'artes-y-actividades-manuales'),
    ('Pintura - Avanzado', 'artes-y-actividades-manuales'),
    ('Pintura decorativa', 'artes-y-actividades-manuales'),
    ('Pintura de la cara', 'artes-y-actividades-manuales'),
    ('Pintura sobre tela', 'artes-y-actividades-manuales'),
    ('Pintura sobre vidrio', 'artes-y-actividades-manuales'),
    ('Pirograbado', 'artes-y-actividades-manuales'),
    ('Plastimodelismo', 'artes-y-actividades-manuales'),
    ('Poesía y Composición', 'artes-y-actividades-manuales'),
    ('Presas y diques', 'artes-y-actividades-manuales'),
    ('Puentes', 'artes-y-actividades-manuales'),
    ('Raku', 'artes-y-actividades-manuales'),
    ('Regata de botes de juguete', 'artes-y-actividades-manuales'),
    ('Regata de botes de juguete - Avanzado', 'artes-y-actividades-manuales'),
    ('Serigrafía', 'artes-y-actividades-manuales'),
    ('Serigrafía - Avanzado', 'artes-y-actividades-manuales'),
    ('Silbatos', 'artes-y-actividades-manuales'),
    ('Silbatos - Avanzado', 'artes-y-actividades-manuales'),
    ('Tallado en madera', 'artes-y-actividades-manuales'),
    ('Tapicería', 'artes-y-actividades-manuales'),
    ('Tarjetas postales', 'artes-y-actividades-manuales'),
    ('Tarjetas postales - Avanzado', 'artes-y-actividades-manuales'),
    ('Techado con paja', 'artes-y-actividades-manuales'),
    ('Tejer', 'artes-y-actividades-manuales'),
    ('Tejer - Avanzado', 'artes-y-actividades-manuales'),
    ('Tejido en malla plástica', 'artes-y-actividades-manuales'),
    ('Tejido en malla plástica - Avanzado', 'artes-y-actividades-manuales'),
    ('Teñido anudado', 'artes-y-actividades-manuales'),
    ('Teñido anudado - Avanzado', 'artes-y-actividades-manuales'),
    ('Tipografía xilográfica', 'artes-y-actividades-manuales'),
    ('Trabajos de aguja', 'artes-y-actividades-manuales'),
    ('Trabajos en cuero', 'artes-y-actividades-manuales'),
    ('Trabajos en cuero - Avanzado', 'artes-y-actividades-manuales'),
    ('Trabajos en fieltro', 'artes-y-actividades-manuales'),
    ('Trabajos en jabón', 'artes-y-actividades-manuales'),
    ('Trabajos en jabón - Avanzado', 'artes-y-actividades-manuales'),
    ('Trabajos en madera', 'artes-y-actividades-manuales'),
    ('Trabajos en metal', 'artes-y-actividades-manuales'),
    ('Trabajos en telar', 'artes-y-actividades-manuales'),
    ('Trabajos en vidrio', 'artes-y-actividades-manuales'),
    ('Tradición aborigen', 'artes-y-actividades-manuales'),
    ('Tradición africana', 'artes-y-actividades-manuales'),
    ('Tradición maorí', 'artes-y-actividades-manuales'),
    ('Tren modelismo', 'artes-y-actividades-manuales'),
    ('Trenzado', 'artes-y-actividades-manuales'),
    ('Trenzado - Avanzado', 'artes-y-actividades-manuales'),
    ('Amarres', 'actividades-recreacionales'),
    ('Amarres - Avanzado', 'actividades-recreacionales'),
    ('Arte de acampar', 'actividades-recreacionales'),
    ('Baloncesto', 'actividades-recreacionales'),
    ('Balonmano', 'actividades-recreacionales'),
    ('Boliche', 'actividades-recreacionales'),
    ('Buceo', 'actividades-recreacionales'),
    ('Buceo con escafandra', 'actividades-recreacionales'),
    ('Buceo con escafandra - Avanzado', 'actividades-recreacionales'),
    ('Bushcraft', 'actividades-recreacionales'),
    ('Búsqueda de gemas', 'actividades-recreacionales'),
    ('Campamento I', 'actividades-recreacionales'),
    ('Campamento II', 'actividades-recreacionales'),
    ('Campamento III', 'actividades-recreacionales'),
    ('Campamento IV', 'actividades-recreacionales'),
    ('Campamento consciente', 'actividades-recreacionales'),
    ('Campamento en invierno', 'actividades-recreacionales'),
    ('Camporí seguro', 'actividades-recreacionales'),
    ('Especialidad JA Canicas', 'actividades-recreacionales'),
    ('Canotaje', 'actividades-recreacionales'),
    ('Canotaje - Avanzado', 'actividades-recreacionales'),
    ('Carritos de rueditas', 'actividades-recreacionales'),
    ('Ciclismo', 'actividades-recreacionales'),
    ('Ciclismo - Avanzado', 'actividades-recreacionales'),
    ('Ciclismo en montaña', 'actividades-recreacionales'),
    ('Ciclismo en montaña - Avanzado', 'actividades-recreacionales'),
    ('Clavado en trampolín', 'actividades-recreacionales'),
    ('Cocinando en olla holandesa', 'actividades-recreacionales'),
    ('Cocina segura', 'actividades-recreacionales'),
    ('Coleccionista', 'actividades-recreacionales'),
    ('Cometas', 'actividades-recreacionales'),
    ('Comida cruda', 'actividades-recreacionales'),
    ('Construcción de canoas', 'actividades-recreacionales'),
    ('Construcciones rústicas', 'actividades-recreacionales'),
    ('Construcciones rústicas - Avanzado', 'actividades-recreacionales'),
    ('Especialidad JA Cubo de Rubik', 'actividades-recreacionales'),
    ('Cuerdas altas', 'actividades-recreacionales'),
    ('Cuerdas altas - Avanzado', 'actividades-recreacionales'),
    ('Deportes adaptados', 'actividades-recreacionales'),
    ('Educación física', 'actividades-recreacionales'),
    ('Ejercicios y marchas', 'actividades-recreacionales'),
    ('Ejercicios y marchas - Avanzado', 'actividades-recreacionales'),
    ('Equitación', 'actividades-recreacionales'),
    ('Equitación - Avanzado', 'actividades-recreacionales'),
    ('Escalada', 'actividades-recreacionales'),
    ('Escalada - Avanzado', 'actividades-recreacionales'),
    ('Escalada en el interior', 'actividades-recreacionales'),
    ('Espeología', 'actividades-recreacionales'),
    ('Espeología - Avanzado', 'actividades-recreacionales'),
    ('Esquí acuático', 'actividades-recreacionales'),
    ('Esquí acuático - Avanzado', 'actividades-recreacionales'),
    ('Esquí alpino', 'actividades-recreacionales'),
    ('Esquí de fondo', 'actividades-recreacionales'),
    ('Evolución en orden cerrado', 'actividades-recreacionales'),
    ('Excursionismo', 'actividades-recreacionales'),
    ('Excursionismo - Avanzado', 'actividades-recreacionales'),
    ('Fogatas y cocina al aire libre', 'actividades-recreacionales'),
    ('Fútbol', 'actividades-recreacionales'),
    ('Fútbol bandera', 'actividades-recreacionales'),
    ('Fútbol de botones', 'actividades-recreacionales'),
    ('Fútbol sala', 'actividades-recreacionales'),
    ('Geocaching (Búsqueda por GPS)', 'actividades-recreacionales'),
    ('Geocaching - Avanzado', 'actividades-recreacionales'),
    ('Geocaching geológico', 'actividades-recreacionales'),
    ('Geocaching geológico - Avanzado', 'actividades-recreacionales'),
    ('Gimnasia', 'actividades-recreacionales'),
    ('Gimnasia - Avanzado', 'actividades-recreacionales'),
    ('Golf', 'actividades-recreacionales'),
    ('Golf de disco', 'actividades-recreacionales'),
    ('Grandes construcciones rústicas', 'actividades-recreacionales'),
    ('Instructor de seguridad en el agua', 'actividades-recreacionales'),
    ('Instructor de seguridad en el agua - Avanzado', 'actividades-recreacionales'),
    ('Intercambio de pins (División Sudamericana)', 'actividades-recreacionales'),
    ('Kayak', 'actividades-recreacionales'),
    ('Espeicalidad JA de Kneeboard', 'actividades-recreacionales'),
    ('Lancha a motor', 'actividades-recreacionales'),
    ('Letterboxing', 'actividades-recreacionales'),
    ('Letterboxing - Avanzado', 'actividades-recreacionales'),
    ('Liderazgo al aire libre', 'actividades-recreacionales'),
    ('Liderazgo al aire libre - Avanzado', 'actividades-recreacionales'),
    ('Liderazgo en la naturaleza', 'actividades-recreacionales'),
    ('Liderazgo en la naturaleza - Avanzado', 'actividades-recreacionales'),
    ('Malabarismo', 'actividades-recreacionales'),
    ('Monociclismo', 'actividades-recreacionales'),
    ('Natación I', 'actividades-recreacionales'),
    ('Natación I - Avanzado', 'actividades-recreacionales'),
    ('Natación II', 'actividades-recreacionales'),
    ('Natación III', 'actividades-recreacionales'),
    ('Natación III - Avanzado', 'actividades-recreacionales'),
    ('Navegación', 'actividades-recreacionales'),
    ('Navegación a vela', 'actividades-recreacionales'),
    ('Nudos', 'actividades-recreacionales'),
    ('Nudos - Avanzado', 'actividades-recreacionales'),
    ('Orientación', 'actividades-recreacionales'),
    ('Orientación (División del Pacífico Sur)', 'actividades-recreacionales'),
    ('Orientación con GPS', 'actividades-recreacionales'),
    ('Parques nacionales y sitios patrimoniales', 'actividades-recreacionales'),
    ('Parques nacionales y sitios patrimoniales - Avanzado', 'actividades-recreacionales'),
    ('Patines', 'actividades-recreacionales'),
    ('Patineta', 'actividades-recreacionales'),
    ('Pesca de trucha', 'actividades-recreacionales'),
    ('Pesca de trucha - Avanzado', 'actividades-recreacionales'),
    ('Petanca', 'actividades-recreacionales'),
    ('Pickleball', 'actividades-recreacionales'),
    ('Pionerismo', 'actividades-recreacionales'),
    ('Pista y campo', 'actividades-recreacionales'),
    ('Prospección de oro', 'actividades-recreacionales'),
    ('Prospección de oro - Avanzado', 'actividades-recreacionales'),
    ('Rafting', 'actividades-recreacionales'),
    ('Rápel', 'actividades-recreacionales'),
    ('Rápel - Avanzado', 'actividades-recreacionales'),
    ('Remo', 'actividades-recreacionales'),
    ('Seguridad básica en el agua', 'actividades-recreacionales'),
    ('Seguridad en el campamento', 'actividades-recreacionales'),
    ('Seguridad en el campamento - Avanzado', 'actividades-recreacionales'),
    ('Señales de senderos', 'actividades-recreacionales'),
    ('Senderismo', 'actividades-recreacionales'),
    ('Senderismo - Avanzado', 'actividades-recreacionales'),
    ('Senderismo con raquetas de nieve', 'actividades-recreacionales'),
    ('Senderismo con raquetas de nieve - Avanzado', 'actividades-recreacionales'),
    ('Especialidad JA Slackline', 'actividades-recreacionales'),
    ('Snowboard', 'actividades-recreacionales'),
    ('Socorrismo', 'actividades-recreacionales'),
    ('Socorrismo - Avanzado', 'actividades-recreacionales'),
    ('Softbol', 'actividades-recreacionales'),
    ('Supervivencia en clima frío', 'actividades-recreacionales'),
    ('Surf', 'actividades-recreacionales'),
    ('Surf a vela', 'actividades-recreacionales'),
    ('Tabla de esquí acuático', 'actividades-recreacionales'),
    ('Tamboreo y percusión', 'actividades-recreacionales'),
    ('Tambores y percusión - Avanzado', 'actividades-recreacionales'),
    ('Telecartofilia', 'actividades-recreacionales'),
    ('Telecartofilia - Avanzado', 'actividades-recreacionales'),
    ('Tenis', 'actividades-recreacionales'),
    ('Tenis de mesa', 'actividades-recreacionales'),
    ('Tiendas de campaña', 'actividades-recreacionales'),
    ('Tiro con arco', 'actividades-recreacionales'),
    ('Tiro con arco - Avanzado', 'actividades-recreacionales'),
    ('Trepar árboles', 'actividades-recreacionales'),
    ('Triatlón', 'actividades-recreacionales'),
    ('Triatlón - Avanzado', 'actividades-recreacionales'),
    ('Trompos', 'actividades-recreacionales'),
    ('Ultimate disc', 'actividades-recreacionales'),
    ('Ultimate disc - Avanzado', 'actividades-recreacionales'),
    ('Vexilología', 'actividades-recreacionales'),
    ('Viajes', 'actividades-recreacionales'),
    ('Viajes - Avanzado', 'actividades-recreacionales'),
    ('Vida primitiva', 'actividades-recreacionales'),
    ('Voleibol', 'actividades-recreacionales'),
    ('Waveboarding', 'actividades-recreacionales'),
    ('Administración', 'actividades-vocacionales'),
    ('Agrimensura', 'actividades-vocacionales'),
    ('Albañilería', 'actividades-vocacionales'),
    ('Arboricultura', 'actividades-vocacionales'),
    ('Arte cristiano de vender', 'actividades-vocacionales'),
    ('Aviadores', 'actividades-vocacionales'),
    ('Banderas náuticas', 'actividades-vocacionales'),
    ('Bibliotecología', 'actividades-vocacionales'),
    ('Blogs', 'actividades-vocacionales'),
    ('Carpintería', 'actividades-vocacionales'),
    ('Código Morse', 'actividades-vocacionales'),
    ('Código de semáforo', 'actividades-vocacionales'),
    ('Computación I - Básico', 'actividades-vocacionales'),
    ('Computación II - Intermedio', 'actividades-vocacionales'),
    ('Computación III - Regular', 'actividades-vocacionales'),
    ('Computación IV - Avanzado', 'actividades-vocacionales'),
    ('Computación V - Especializado', 'actividades-vocacionales'),
    ('Computadoras', 'actividades-vocacionales'),
    ('Computadoras - Avanzado', 'actividades-vocacionales'),
    ('Comunicaciones', 'actividades-vocacionales'),
    ('Comunicaciones II', 'actividades-vocacionales'),
    ('Contabilidad I', 'actividades-vocacionales'),
    ('Contabilidad II', 'actividades-vocacionales'),
    ('Criptografía (División Norteamericana)', 'actividades-vocacionales'),
    ('Criptografía (Unión de Asia del Sureste)', 'actividades-vocacionales'),
    ('Criptografía - avanzado', 'actividades-vocacionales'),
    ('Crítica de medios visuales', 'actividades-vocacionales'),
    ('Cuidado y mantenimiento de guitarras', 'actividades-vocacionales'),
    ('Desarrollo de software', 'actividades-vocacionales'),
    ('Diseñador de web', 'actividades-vocacionales'),
    ('Diseñador de web - Avanzado', 'actividades-vocacionales'),
    ('Drones', 'actividades-vocacionales'),
    ('Electricidad', 'actividades-vocacionales'),
    ('Electrónica', 'actividades-vocacionales'),
    ('Empapelado', 'actividades-vocacionales'),
    ('Encuadernación', 'actividades-vocacionales'),
    ('Ensamblaje y mantenimiento de computadoras', 'actividades-vocacionales'),
    ('Enseñanza', 'actividades-vocacionales'),
    ('Evanglismo bíblico', 'actividades-vocacionales'),
    ('Fabricación de jabón', 'actividades-vocacionales'),
    ('Fabricación de jabón - Avanzado', 'actividades-vocacionales'),
    ('Fontanería (Plomería)', 'actividades-vocacionales'),
    ('Fundición de peltre', 'actividades-vocacionales'),
    ('Herrería', 'actividades-vocacionales'),
    ('Imprenta', 'actividades-vocacionales'),
    ('Información programable', 'actividades-vocacionales'),
    ('Ingeniería', 'actividades-vocacionales'),
    ('Inteligencia artificial', 'actividades-vocacionales'),
    ('Internet', 'actividades-vocacionales'),
    ('Internet - Avanzado', 'actividades-vocacionales'),
    ('Instalación de azulejos', 'actividades-vocacionales'),
    ('Intérprete de lenguaje de señas', 'actividades-vocacionales'),
    ('Logística', 'actividades-vocacionales'),
    ('Manejo y mantenimiento de impresoras', 'actividades-vocacionales'),
    ('Mantenimiento de bicicletas', 'actividades-vocacionales'),
    ('Mecánica de automóviles', 'actividades-vocacionales'),
    ('Mecánica de automóviles - Avanzado', 'actividades-vocacionales'),
    ('Mecanografía', 'actividades-vocacionales'),
    ('Mercadotecnia', 'actividades-vocacionales'),
    ('Mercadotecnia - Avanzado', 'actividades-vocacionales'),
    ('Modelado textil', 'actividades-vocacionales'),
    ('Motores pequeños', 'actividades-vocacionales'),
    ('Negocios', 'actividades-vocacionales'),
    ('Nociones de derecho', 'actividades-vocacionales'),
    ('Nociones de economía', 'actividades-vocacionales'),
    ('Podcasting', 'actividades-vocacionales'),
    ('Peluquería', 'actividades-vocacionales'),
    ('Periodismo', 'actividades-vocacionales'),
    ('Pintura exterior de casas', 'actividades-vocacionales'),
    ('Pintura interior de casas', 'actividades-vocacionales'),
    ('Preparación y prevención de incendios forestales', 'actividades-vocacionales'),
    ('Procesar texto', 'actividades-vocacionales'),
    ('Procesar texto (División del Pacífico Sur)', 'actividades-vocacionales'),
    ('Radio', 'actividades-vocacionales'),
    ('Radio - Avanzado', 'actividades-vocacionales'),
    ('Radio de banda ciudadana', 'actividades-vocacionales'),
    ('Radioelectrónica', 'actividades-vocacionales'),
    ('Recaudación de fondos', 'actividades-vocacionales'),
    ('Redes sociales', 'actividades-vocacionales'),
    ('Reparación de calzado', 'actividades-vocacionales'),
    ('Restauración y conservación de documentos', 'actividades-vocacionales'),
    ('Robótica', 'actividades-vocacionales'),
    ('Robótica - Avanzado', 'actividades-vocacionales'),
    ('Salud y curación (División Norteamericana)', 'actividades-vocacionales'),
    ('Secretariado', 'actividades-vocacionales'),
    ('Seguridad ante incendios', 'actividades-vocacionales'),
    ('Seguridad en las redes sociales', 'actividades-vocacionales'),
    ('Signos, señales y símbolos', 'actividades-vocacionales'),
    ('Sivicultura', 'actividades-vocacionales'),
    ('Silvicutltura - Avanzado', 'actividades-vocacionales'),
    ('Soldadura', 'actividades-vocacionales'),
    ('Soldadura (División Norteamericana)', 'actividades-vocacionales'),
    ('Taquigrafía', 'actividades-vocacionales'),
    ('Técnico de audio', 'actividades-vocacionales'),
    ('Tecnología móvil', 'actividades-vocacionales'),
    ('Torno mecánico', 'actividades-vocacionales'),
    ('Trabajos en madera', 'actividades-vocacionales'),
    ('Video (Asociación General)', 'actividades-vocacionales'),
    ('Video (División Norteamericana)', 'actividades-vocacionales'),
    ('Video - Avanzado', 'actividades-vocacionales'),
    ('Acolchado', 'artes-domesticas'),
    ('Alimentos congelados', 'artes-domesticas'),
    ('Arte culinario', 'artes-domesticas'),
    ('Arte culinario - Avanzado', 'artes-domesticas'),
    ('Chocolate', 'artes-domesticas'),
    ('Cocinando pizzas', 'artes-domesticas'),
    ('Conservación de alimentos', 'artes-domesticas'),
    ('Corte y confección', 'artes-domesticas'),
    ('Corte y confección - Avanzado', 'artes-domesticas'),
    ('Costura básica', 'artes-domesticas'),
    ('Deshidratación de alimentos', 'artes-domesticas'),
    ('Economía doméstica', 'artes-domesticas'),
    ('Fabricación de esteras', 'artes-domesticas'),
    ('Haystacks', 'artes-domesticas'),
    ('Lavado y planchado', 'artes-domesticas'),
    ('Mantenimiento del hogar', 'artes-domesticas'),
    ('Nutrición', 'artes-domesticas'),
    ('Nutrición - Avanzado', 'artes-domesticas'),
    ('Panadería', 'artes-domesticas'),
    ('Preparación de comidas culturales', 'artes-domesticas'),
    ('Presupuesto familiar (División Norteamericana)', 'artes-domesticas'),
    ('Presupuesto familiar (División Sudamericana)', 'artes-domesticas'),
    ('Producción de pizzas', 'artes-domesticas'),
    ('Sastrería', 'artes-domesticas'),
    ('Vestidos de Tapa', 'artes-domesticas'),
    ('Adoración cristiana', 'crecimiento-espiritual'),
    ('Alabanza y adoración', 'crecimiento-espiritual'),
    ('Apocalipsis', 'crecimiento-espiritual'),
    ('Aprecio del sábado', 'crecimiento-espiritual'),
    ('Arqueología bíblica', 'crecimiento-espiritual'),
    ('Arte cristiano de predicar', 'crecimiento-espiritual'),
    ('Arte cristiano de predicar - Avanzado', 'crecimiento-espiritual'),
    ('Audio y sonido', 'crecimiento-espiritual'),
    ('Audio y sonido - Avanzado', 'crecimiento-espiritual'),
    ('Auslan (Lenguaje de señas australiano)', 'crecimiento-espiritual'),
    ('Auslan (Lenguaje de señas australiano) - Avanzado', 'crecimiento-espiritual'),
    ('Aventuro para Cristo', 'crecimiento-espiritual'),
    ('Aventuro para Cristo - Avanzado', 'crecimiento-espiritual'),
    ('Banderas', 'crecimiento-espiritual'),
    ('Banderas - Avanzado', 'crecimiento-espiritual'),
    ('Banderas de Australia', 'crecimiento-espiritual'),
    ('Banderas de Australia, advanced', 'crecimiento-espiritual'),
    ('Braille', 'crecimiento-espiritual'),
    ('Buena conducta escolar', 'crecimiento-espiritual'),
    ('Carrozas de desfile', 'crecimiento-espiritual'),
    ('Carrozas de desfile - Avanzado', 'crecimiento-espiritual'),
    ('Ceremonias', 'crecimiento-espiritual'),
    ('Civismo cristiano', 'crecimiento-espiritual'),
    ('Colportaje', 'crecimiento-espiritual'),
    ('Conciencia de discapacidad', 'crecimiento-espiritual'),
    ('Conciencia de los discapacitados en Australia', 'crecimiento-espiritual'),
    ('Conciencia de los discapacitados en Australia - Avanzado', 'crecimiento-espiritual'),
    ('Creacionismo', 'crecimiento-espiritual'),
    ('Creacionismo - Avanzado', 'crecimiento-espiritual'),
    ('Crítico de medios', 'crecimiento-espiritual'),
    ('Cuidado de niños', 'crecimiento-espiritual'),
    ('Cultura Sudamericana', 'crecimiento-espiritual'),
    ('Día ANZAC', 'crecimiento-espiritual'),
    ('Dirección de menores', 'crecimiento-espiritual'),
    ('Discípulos y apóstoles', 'crecimiento-espiritual'),
    ('Drama cristiano', 'crecimiento-espiritual'),
    ('Educación inclusiva', 'crecimiento-espiritual'),
    ('El diluvio de Noé', 'crecimiento-espiritual'),
    ('Escatología', 'crecimiento-espiritual'),
    ('Espíritu de Profecía', 'crecimiento-espiritual'),
    ('Estudio bíblico en grupo pequeño', 'crecimiento-espiritual'),
    ('Estudio bíblico en grupo pequeño - Avanzado', 'crecimiento-espiritual'),
    ('Evangelismo personal', 'crecimiento-espiritual'),
    ('Evangelismo web', 'crecimiento-espiritual'),
    ('Evangelismo web - Avanzado', 'crecimiento-espiritual'),
    ('Formación de equipos cristianos', 'crecimiento-espiritual'),
    ('Heráldica', 'crecimiento-espiritual'),
    ('Heráldica - Avanzado', 'crecimiento-espiritual'),
    ('Herencia adventista afroamericana', 'crecimiento-espiritual'),
    ('Herencia adventista afroamericana - Avanzado', 'crecimiento-espiritual'),
    ('Herencia de los pioneros adventistas', 'crecimiento-espiritual'),
    ('Himnos', 'crecimiento-espiritual'),
    ('Historia A}adventista', 'crecimiento-espiritual'),
    ('Historia y herencia australiana adventista del séptimo día', 'crecimiento-espiritual'),
    ('Historiador ecelsiástico', 'crecimiento-espiritual'),
    ('Idiomas', 'crecimiento-espiritual'),
    ('Inteligencia emocional', 'crecimiento-espiritual'),
    ('Intercesor', 'crecimiento-espiritual'),
    ('Interpretación bíblica', 'crecimiento-espiritual'),
    ('Investigador bíblico', 'crecimiento-espiritual'),
    ('Jueces de Israel', 'crecimiento-espiritual'),
    ('Lenguaje bíblico (hebreo)', 'crecimiento-espiritual'),
    ('Lenguaje bíblico (hebreo) - Avanzado', 'crecimiento-espiritual'),
    ('Lenguaje de signos', 'crecimiento-espiritual'),
    ('Lenguaje de signos - Avanzado', 'crecimiento-espiritual'),
    ('Libro de Daniel', 'crecimiento-espiritual'),
    ('Marcado de la Biblia', 'crecimiento-espiritual'),
    ('Marcado de la Biblia - Avanzado', 'crecimiento-espiritual'),
    ('Mayordomía', 'crecimiento-espiritual'),
    ('Memorizar la Biblia', 'crecimiento-espiritual'),
    ('Mensajera de Dios', 'crecimiento-espiritual'),
    ('Mensajes de los tres ángeles', 'crecimiento-espiritual'),
    ('Ministerio de transmisión de medios', 'crecimiento-espiritual'),
    ('Modales y apariencia cristiana', 'crecimiento-espiritual'),
    ('Mujeres en la historia adventista', 'crecimiento-espiritual'),
    ('Multiculturalidad', 'crecimiento-espiritual'),
    ('Narración de historias cristianas', 'crecimiento-espiritual'),
    ('Optimismo', 'crecimiento-espiritual'),
    ('Oración', 'crecimiento-espiritual'),
    ('Oración - Avanzado', 'crecimiento-espiritual'),
    ('Pacificador', 'crecimiento-espiritual'),
    ('Pacificador - Avanzado', 'crecimiento-espiritual'),
    ('Parábolas de Jesús', 'crecimiento-espiritual'),
    ('Patriarcas de la Biblia', 'crecimiento-espiritual'),
    ('Patriotismo', 'crecimiento-espiritual'),
    ('Pioneros adventistas', 'crecimiento-espiritual'),
    ('Predicar', 'crecimiento-espiritual'),
    ('Predicar - Avanzado', 'crecimiento-espiritual'),
    ('Prevención de acoso I', 'crecimiento-espiritual'),
    ('Prevención de acoso II', 'crecimiento-espiritual'),
    ('Primeros misioneros adventistas', 'crecimiento-espiritual'),
    ('Profetas y profecía', 'crecimiento-espiritual'),
    ('Profetas y profecía - Avanzado', 'crecimiento-espiritual'),
    ('Relaciones saludables', 'crecimiento-espiritual'),
    ('Reyes de Israel', 'crecimiento-espiritual'),
    ('Santuario', 'crecimiento-espiritual'),
    ('Santuario - Avanzado', 'crecimiento-espiritual'),
    ('Tecnología antigua', 'crecimiento-espiritual'),
    ('Temperancia', 'crecimiento-espiritual'),
    ('Testificación de menores', 'crecimiento-espiritual'),
    ('The Hopeful', 'crecimiento-espiritual'),
    ('Títeres', 'crecimiento-espiritual'),
    ('Títeres - Avanzado', 'crecimiento-espiritual'),
    ('Transformador del mundo', 'crecimiento-espiritual'),
    ('Transmisiones de cultos en línea', 'crecimiento-espiritual'),
    ('Trata de personas', 'crecimiento-espiritual'),
    ('Viajes misioneros al extranjero', 'crecimiento-espiritual'),
    ('Vida familiar', 'crecimiento-espiritual'),
    ('Vida misionera', 'crecimiento-espiritual'),
    ('Visitación cristiana', 'crecimiento-espiritual'),
    ('Abejas y avispas', 'estudio-de-la-naturaleza'),
    ('Acacias', 'estudio-de-la-naturaleza'),
    ('Acuarios', 'estudio-de-la-naturaleza'),
    ('Agricultura ecológica', 'estudio-de-la-naturaleza'),
    ('Algas marinas', 'estudio-de-la-naturaleza'),
    ('Anfibios', 'estudio-de-la-naturaleza'),
    ('Anfibios - Avanzado', 'estudio-de-la-naturaleza'),
    ('Animales domésticos', 'estudio-de-la-naturaleza'),
    ('Animales migratorios', 'estudio-de-la-naturaleza'),
    ('Animales nocivos', 'estudio-de-la-naturaleza'),
    ('Animales nocturnos', 'estudio-de-la-naturaleza'),
    ('Animales venenosos', 'estudio-de-la-naturaleza'),
    ('Antílopes', 'estudio-de-la-naturaleza'),
    ('Antílopes - Avanzado', 'estudio-de-la-naturaleza'),
    ('Arácnidos', 'estudio-de-la-naturaleza'),
    ('Árboles', 'estudio-de-la-naturaleza'),
    ('Árboles - Avanzado', 'estudio-de-la-naturaleza'),
    ('Arbustos', 'estudio-de-la-naturaleza'),
    ('Arbustos - Avanzado', 'estudio-de-la-naturaleza'),
    ('Arena', 'estudio-de-la-naturaleza'),
    ('Arrecifes de Coral', 'estudio-de-la-naturaleza'),
    ('Arrecifes de coral - Avanzado', 'estudio-de-la-naturaleza'),
    ('Aves', 'estudio-de-la-naturaleza'),
    ('Aves - Avanzado', 'estudio-de-la-naturaleza'),
    ('Aves australianas', 'estudio-de-la-naturaleza'),
    ('Aves domésticas', 'estudio-de-la-naturaleza'),
    ('Aves de jaula', 'estudio-de-la-naturaleza'),
    ('Aves de rapiña', 'estudio-de-la-naturaleza'),
    ('Aves de rapiña - Avanzado', 'estudio-de-la-naturaleza'),
    ('Aves de rapiña (División Sudamericana)', 'estudio-de-la-naturaleza'),
    ('Azúcar de Arce', 'estudio-de-la-naturaleza'),
    ('Azúcar de Arce - Avanzado', 'estudio-de-la-naturaleza'),
    ('Bacterias', 'estudio-de-la-naturaleza'),
    ('Bioconstrucción', 'estudio-de-la-naturaleza'),
    ('Bosques templados caducifolios', 'estudio-de-la-naturaleza'),
    ('Briófitas', 'estudio-de-la-naturaleza'),
    ('Bromelias', 'estudio-de-la-naturaleza'),
    ('Burbujas', 'estudio-de-la-naturaleza'),
    ('Cactus', 'estudio-de-la-naturaleza'),
    ('Cactus - Avanzado', 'estudio-de-la-naturaleza'),
    ('Camellos', 'estudio-de-la-naturaleza'),
    ('Camuflaje animal', 'estudio-de-la-naturaleza'),
    ('Camuflaje animal - Avanzado', 'estudio-de-la-naturaleza'),
    ('Carbón', 'estudio-de-la-naturaleza'),
    ('Cataratas', 'estudio-de-la-naturaleza'),
    ('Cetáceos', 'estudio-de-la-naturaleza'),
    ('Ciencia de agua', 'estudio-de-la-naturaleza'),
    ('Ciencia de agua - Avanzado', 'estudio-de-la-naturaleza'),
    ('Ciencia del clima', 'estudio-de-la-naturaleza'),
    ('Ciencia del clima - Avanzado', 'estudio-de-la-naturaleza'),
    ('Ciencia planetaria', 'estudio-de-la-naturaleza'),
    ('Cigarras', 'estudio-de-la-naturaleza'),
    ('Citología', 'estudio-de-la-naturaleza'),
    ('Climatología', 'estudio-de-la-naturaleza'),
    ('Combustibles alternativos', 'estudio-de-la-naturaleza'),
    ('Combustibles alternativos - Avanzado', 'estudio-de-la-naturaleza'),
    ('Compostaje casero', 'estudio-de-la-naturaleza'),
    ('Conservación ambiental', 'estudio-de-la-naturaleza'),
    ('Coquí', 'estudio-de-la-naturaleza'),
    ('Coquí - Avanzado', 'estudio-de-la-naturaleza'),
    ('Cosmografía', 'estudio-de-la-naturaleza'),
    ('Cosmografía - Avanzado', 'estudio-de-la-naturaleza'),
    ('Crustáceos', 'estudio-de-la-naturaleza'),
    ('Cuidado y entrenamiento de perros', 'estudio-de-la-naturaleza'),
    ('Dinosaurios', 'estudio-de-la-naturaleza'),
    ('Dunas', 'estudio-de-la-naturaleza'),
    ('Dunas - Avanzado', 'estudio-de-la-naturaleza'),
    ('Ecología', 'estudio-de-la-naturaleza'),
    ('Ecología - Avanzado', 'estudio-de-la-naturaleza'),
    ('Energía renovable', 'estudio-de-la-naturaleza'),
    ('Energías renovables', 'estudio-de-la-naturaleza'),
    ('Especies en peligro de extinción', 'estudio-de-la-naturaleza'),
    ('Estuarios', 'estudio-de-la-naturaleza'),
    ('Eucaliptos', 'estudio-de-la-naturaleza'),
    ('Fauna marina', 'estudio-de-la-naturaleza'),
    ('Fisiología vegetal', 'estudio-de-la-naturaleza'),
    ('Flores', 'estudio-de-la-naturaleza'),
    ('Flores - Avanzado', 'estudio-de-la-naturaleza'),
    ('Fósiles', 'estudio-de-la-naturaleza'),
    ('Gatos', 'estudio-de-la-naturaleza'),
    ('Gatos - Avanzado', 'estudio-de-la-naturaleza'),
    ('Geología', 'estudio-de-la-naturaleza'),
    ('Geología - Avanzado', 'estudio-de-la-naturaleza'),
    ('Glaciares', 'estudio-de-la-naturaleza'),
    ('Gramíneas', 'estudio-de-la-naturaleza'),
    ('Helechos', 'estudio-de-la-naturaleza'),
    ('Hierbas', 'estudio-de-la-naturaleza'),
    ('Hormigas', 'estudio-de-la-naturaleza'),
    ('Hongos', 'estudio-de-la-naturaleza'),
    ('Huellas de animales', 'estudio-de-la-naturaleza'),
    ('Huellas de animales - Avanzado', 'estudio-de-la-naturaleza'),
    ('Insectos', 'estudio-de-la-naturaleza'),
    ('Insectos - Avanzado', 'estudio-de-la-naturaleza'),
    ('Invertebrados marinos', 'estudio-de-la-naturaleza'),
    ('Líquenes', 'estudio-de-la-naturaleza'),
    ('Líquenes, hepáticas y musgos', 'estudio-de-la-naturaleza'),
    ('Lombrices', 'estudio-de-la-naturaleza'),
    ('Lombrices - Avanzado', 'estudio-de-la-naturaleza'),
    ('Loros y cacatúas', 'estudio-de-la-naturaleza'),
    ('Mamíferos', 'estudio-de-la-naturaleza'),
    ('Mamíferos - Avanzado', 'estudio-de-la-naturaleza'),
    ('Mamíferos marinos', 'estudio-de-la-naturaleza'),
    ('Mamíferos pequeños como mascotas', 'estudio-de-la-naturaleza'),
    ('Mariposas', 'estudio-de-la-naturaleza'),
    ('Marsupiales', 'estudio-de-la-naturaleza'),
    ('Medio ambiente acuático', 'estudio-de-la-naturaleza'),
    ('Medio ambiente terrestre', 'estudio-de-la-naturaleza'),
    ('Meteoritos', 'estudio-de-la-naturaleza'),
    ('Migración', 'estudio-de-la-naturaleza'),
    ('Mineralogía', 'estudio-de-la-naturaleza'),
    ('Mineralogía - Avanzado', 'estudio-de-la-naturaleza'),
    ('Moluscos', 'estudio-de-la-naturaleza'),
    ('Moluscos - Avanzado', 'estudio-de-la-naturaleza'),
    ('Moluscos terrestres y de agua dulce', 'estudio-de-la-naturaleza'),
    ('Montañas', 'estudio-de-la-naturaleza'),
    ('Murciélagos', 'estudio-de-la-naturaleza'),
    ('Murciélagos - Avanzado', 'estudio-de-la-naturaleza'),
    ('Océanos', 'estudio-de-la-naturaleza'),
    ('Odonatos', 'estudio-de-la-naturaleza'),
    ('Odonatos - Avanzado', 'estudio-de-la-naturaleza'),
    ('Orquídeas', 'estudio-de-la-naturaleza'),
    ('Orquídeas - Avanzado', 'estudio-de-la-naturaleza'),
    ('Palmeras', 'estudio-de-la-naturaleza'),
    ('Papagayos, loros y pericos', 'estudio-de-la-naturaleza'),
    ('Pantanos y ciénagas', 'estudio-de-la-naturaleza'),
    ('Pantanos y ciénagas - Avanzado', 'estudio-de-la-naturaleza'),
    ('Pastizales templados', 'estudio-de-la-naturaleza'),
    ('Pastizales templados - Avanzado', 'estudio-de-la-naturaleza'),
    ('Peces', 'estudio-de-la-naturaleza'),
    ('Peces ornamentales', 'estudio-de-la-naturaleza'),
    ('Perros', 'estudio-de-la-naturaleza'),
    ('Plantas carnívoras', 'estudio-de-la-naturaleza'),
    ('Plantas de interior', 'estudio-de-la-naturaleza'),
    ('Plantas depredadoras', 'estudio-de-la-naturaleza'),
    ('Plantas silvestres comestibles', 'estudio-de-la-naturaleza'),
    ('Poríferos y cnidarios', 'estudio-de-la-naturaleza'),
    ('Preservación de recursos hídricos', 'estudio-de-la-naturaleza'),
    ('Primates', 'estudio-de-la-naturaleza'),
    ('Protozoarios', 'estudio-de-la-naturaleza'),
    ('Reciclaje - Avanzado', 'estudio-de-la-naturaleza'),
    ('Recogida selectiva', 'estudio-de-la-naturaleza'),
    ('Reptiles', 'estudio-de-la-naturaleza'),
    ('Reptiles - Avanzado', 'estudio-de-la-naturaleza'),
    ('Ríos y arroyos', 'estudio-de-la-naturaleza'),
    ('Ríos y arroyos - Avanzado', 'estudio-de-la-naturaleza'),
    ('Semillas', 'estudio-de-la-naturaleza'),
    ('Semillas - Avanzado', 'estudio-de-la-naturaleza'),
    ('Selvas pluviales', 'estudio-de-la-naturaleza'),
    ('Sol de medianoche', 'estudio-de-la-naturaleza'),
    ('Suelos y terrenos', 'estudio-de-la-naturaleza'),
    ('Taiga', 'estudio-de-la-naturaleza'),
    ('Taiga - Avanzado', 'estudio-de-la-naturaleza'),
    ('Tiburones', 'estudio-de-la-naturaleza'),
    ('Tortugas', 'estudio-de-la-naturaleza'),
    ('Vida microscópica', 'estudio-de-la-naturaleza'),
    ('Volcanes', 'estudio-de-la-naturaleza'),
    ('Alerta roja', 'salud-y-ciencia'),
    ('Anatomía humana', 'salud-y-ciencia'),
    ('Audición', 'salud-y-ciencia'),
    ('Bienestar', 'salud-y-ciencia'),
    ('Bienestar - Avanzado', 'salud-y-ciencia'),
    ('Bioquímica', 'salud-y-ciencia'),
    ('Bioquímica - Avanzado', 'salud-y-ciencia'),
    ('Bioseguridad', 'salud-y-ciencia'),
    ('Búsqueda y rescate', 'salud-y-ciencia'),
    ('Cerebro y conducta', 'salud-y-ciencia'),
    ('Científicos cristianos', 'salud-y-ciencia'),
    ('Conciencia sobre el cáncer', 'salud-y-ciencia'),
    ('Corazón y circulación', 'salud-y-ciencia'),
    ('Determinantes sociales de la salud', 'salud-y-ciencia'),
    ('Digestión', 'salud-y-ciencia'),
    ('Enfermería casera', 'salud-y-ciencia'),
    ('Experimentos científicos', 'salud-y-ciencia'),
    ('Física', 'salud-y-ciencia'),
    ('Gusto', 'salud-y-ciencia'),
    ('Habilidad matemática I', 'salud-y-ciencia'),
    ('Habilidad matemática II', 'salud-y-ciencia'),
    ('Habilidad matemática III', 'salud-y-ciencia'),
    ('Habilidad matemática IV', 'salud-y-ciencia'),
    ('Herencia', 'salud-y-ciencia'),
    ('Higiene oral', 'salud-y-ciencia'),
    ('Higiene oral - Avanzado', 'salud-y-ciencia'),
    ('Huesos, músculos y movimiento', 'salud-y-ciencia'),
    ('Legado de curación', 'salud-y-ciencia'),
    ('Metodología de estudio', 'salud-y-ciencia'),
    ('Ocho claves para la buena salud', 'salud-y-ciencia'),
    ('Olfato', 'salud-y-ciencia'),
    ('Óptica', 'salud-y-ciencia'),
    ('Patrimonio histórico', 'salud-y-ciencia'),
    ('Plantas medicinales', 'salud-y-ciencia'),
    ('Prevención de enfermedades tropicales', 'salud-y-ciencia'),
    ('Primeros auxilios I', 'salud-y-ciencia'),
    ('Primeros auxilios II', 'salud-y-ciencia'),
    ('Primeros auxilios II - Avanzado', 'salud-y-ciencia'),
    ('Primeros auxilios de San Juan', 'salud-y-ciencia'),
    ('Quedarse en casa', 'salud-y-ciencia'),
    ('Química', 'salud-y-ciencia'),
    ('Reanimación cardiopulmonar (RCP)', 'salud-y-ciencia'),
    ('Remedios naturales', 'salud-y-ciencia'),
    ('Rescate básico', 'salud-y-ciencia'),
    ('Respuesta de salud mental de adolescentes', 'salud-y-ciencia'),
    ('Risa', 'salud-y-ciencia'),
    ('Salud y bienestar personal', 'salud-y-ciencia'),
    ('Salud y curación', 'salud-y-ciencia'),
    ('Salud mental', 'salud-y-ciencia'),
    ('Sangre y defensas del cuerpo', 'salud-y-ciencia'),
    ('Sexualidad humana', 'salud-y-ciencia'),
    ('Sistema cardiopulmonar', 'salud-y-ciencia'),
    ('Sistema cardiopulmonar - Avanzado', 'salud-y-ciencia'),
    ('Sistema respiratorio', 'salud-y-ciencia'),
    ('Tacto', 'salud-y-ciencia'),
    ('Tráfico seguro', 'salud-y-ciencia'),
    ('Vacunas', 'salud-y-ciencia'),
    ('Virus', 'salud-y-ciencia'),
    ('Vista', 'salud-y-ciencia'),
    ('Zoonosis', 'salud-y-ciencia')
),
club_tipos AS (
  SELECT nombre FROM public.tipos_club
  WHERE nombre ILIKE 'Conquistador%'
     OR nombre ILIKE 'Gu%Mayor%'
     OR nombre ILIKE 'Master Guide%'
),
resolved AS (
  SELECT
    src.nombre,
    s.id AS seccion_id,
    ct.nombre AS club_tipo
  FROM src
  JOIN public.especialidad_secciones s ON s.slug = src.seccion_slug
  CROSS JOIN club_tipos ct
)
INSERT INTO public.especialidades (nombre, club_tipo, seccion_id)
SELECT r.nombre, r.club_tipo, r.seccion_id
FROM resolved r
WHERE NOT EXISTS (
  SELECT 1 FROM public.especialidades e
  WHERE lower(trim(e.nombre)) = lower(trim(r.nombre))
    AND e.club_tipo = r.club_tipo
    AND e.seccion_id IS NOT DISTINCT FROM r.seccion_id
);

COMMIT;
